# Generated by Django 4.2.1 on 2023-05-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0001_initial'),
        ('traineeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseApp.course', verbose_name='course'),
        ),
    ]
