# Generated by Django 4.2.1 on 2023-05-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traineeApp', '0002_trainee_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email'),
        ),
    ]
