# Generated by Django 4.2.1 on 2023-05-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traineeApp', '0003_alter_trainee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='password',
        ),
        migrations.AddField(
            model_name='trainee',
            name='Class',
            field=models.CharField(default=5, max_length=255, verbose_name='Class'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
