# Generated by Django 4.2.1 on 2023-05-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
